#!/bin/sh
function setup() {
    echo "Create virtualenv $VIRTUAL_ENV"
    if ! test -d ${VIRTUAL_ENV}; then
        export _TESTENV_IN_NEWENV=1
        virtualenv --python=python2.7 ${VIRTUAL_ENV} || return 1
    else
        export _TESTENV_IN_NEWENV=0
    fi
}
VIRTUAL_ENV=${VIRTUAL_ENV:-venv}
if setup; then
    . ${VIRTUAL_ENV}/bin/activate
    export JOBRUNNER_STATE_DIR=${PWD}/cfg/
    if [[ $_TESTENV_IN_NEWENV -eq 1 ]]; then
        pip install --upgrade pip
        pip install --upgrade tox pdbpp ipython
        pip install -r requirements.txt
        python setup.py develop
    fi
fi
